### ISSUE TITLE
USB Mass Storage

### ISSUE THREAD

**Issue by HyperMuffin12** [Flipper-XFW/Xtreme-Firmware#182]
### Description of the feature you're suggesting.

Although being slow, I believe an app for USB Mass Storage would be useful for accessing files from the flipper more conveniently.

Please see https://github.com/flipperdevices/flipperzero-firmware/pull/1060 to get an idea of what I mean.

I also feel an app for Subghz Morse Code SOS could be useful, or an app for inputting text and having it transmitted as Morse Code.

https://github.com/arha/dolphin-sos is similar to what I'm suggesting but crashes on any button press.

**Comment by ClaraCrazy** [comment]
The issue with mass-storage is that its not working properly as of yet. If you have a look on the projects tab, you will see that its something we are already working on. 

as for morse code... I dont see why, as we already have a proper subghz chat, why complicate it with morse?

**Comment by HyperMuffin12** [comment]
I was thinking more so it can be picked up and decoded by someone with a walkie talkie or ham radio.

Might be impractical I'm not sure, but I felt it was worth a suggestion.

**Comment by ClaraCrazy** [comment]
:cathmm: valid

**Comment by TheXHalferX** [comment]
By the way, this idea of emulating Mass Storage form ISO files. The fact, that speed is capped at 500 kb/s is not good, but sometimes (i.e. I have only one computer) not having already flashed drive can be a disaster. I'm trying to investigate code from this [https://github.com/kevinwallace/flipperzero-firmware/tree/mass_storage](url) commit and it seems that it's VERY outdated, but working properly in build (0.50 or smth). Even loading small ISO of minimal Linux can be 15 -30 minutes long. Maybe it is still worth a shot? Anyway, have a great day/night/other, you beautiful devs)

**Comment by Zarcolio** [comment]
Because of the lack of a mass storage function, I wrote a simple Ducky script that launches an executable from a removable drive you hook-up together with a Flipper. Have look at https://github.com/Zarcolio/Duckyscript/blob/main/Ducky%20script/Offensive/ExeFromUsb.txt

![_20230606_173150](https://github.com/ClaraCrazy/Flipper-Xtreme/assets/14904430/62196a05-baa3-44b4-b515-759cb2e39199)

**Comment by Willy-JL** [comment]
mass storage is now working and will be released shortly, sos should go into its own issue.

**Comment by HyperMuffin12** [comment]
Is there any documentation on how to use the app? 

I have put some files in /ext/apps_data/mass_storage/ 

Despite this none of these files appear in that directory when I open the app.

Any help would be appreciated

**Comment by TheXHalferX** [comment]
You should use *.img files to appear in the menu, tested, works great
