### ISSUE TITLE
Apps: CLI: Fix crash on open

### ISSUE THREAD

**Issue by grugnoymeme** [Flipper-XFW/Xtreme-Firmware#323]
### Describe the bug.

Every time i try to open the sub ghz chat cli bridge, flipper crashes: "Flipper Crashed but has been rebooted furi_check failed"

### Reproduction

1. Switch on
2. Press Ok to enter menu
3. Applications
4. Tools
5. CLI (subghz chat)
6. CRASH

**Comment by analyserdmz** [comment]
Same thing here.

**Comment by ClaraCrazy** [comment]
We know. The app keeps breaking every other release. Not our app tho, and therefore it shoulsnt be our job to continuously patch an external app.

**Comment by Willy-JL** [comment]
fixed via 6b99a117ccf7cfbbb35ff17732a8362b76b7f652
