### ISSUE TITLE
Product info clipping

### ISSUE THREAD

**Issue by chrisi2008** [Flipper-XFW/Xtreme-Firmware#332]
### Describe the bug.

In the Battery menu if u go to the right with the EAC CE FC logs there are things clipping

### Reproduction

1. Turn on
2. Hold right to enter Battery menu
3. Press left five times until you see a logo and the text R 210-175991
4. Press right once

### Anything else?

**Not important just wierd**
**Im using the Dev version from 21.07.2023**

**Comment by Willy-JL** [comment]
Closed since only in dev, not present in release. Astra added text and forgot to reset it after showing the dialog screen
