### ISSUE TITLE
Metronome crashes Flipper

### ISSUE THREAD

**Issue by chrisi2008** [Flipper-XFW/Xtreme-Firmware#333]
### Describe the bug.

Flipper crashes when exiting metronome

NULL Pointer dereference

### Reproduction

1. Turn on
2. Navigate to metronome (Apps Media Metronome)
3. Set to 16/16 and 300BPM
4. Wait a few seconds
5. Exit

### Target

crash

**Comment by ClaraCrazy** [comment]
cant replicate, works perfectly fine
