### ISSUE TITLE
BadKB: Show time elapsed since script start

### ISSUE THREAD

**Issue by Zarcolio** [Flipper-XFW/Xtreme-Firmware#335]
### Describe the enhancement you're suggesting.

Sometimes it's good to know how long a BadKB script takes to fully have run. It would be nice if the BadKB app runs a stopwatch during execution.

**Comment by ClaraCrazy** [comment]
The app has no way of knowing how long it takes for a script to run

**Comment by Willy-JL** [comment]
i think they meant a stopwatch rather than a timer. like how long has elapsed since you started the script...

could be doable

**Comment by ClaraCrazy** [comment]
that would make more sense, yes

**Comment by Zarcolio** [comment]
Yes, a stopwatch is what I meant 😅
