### ISSUE TITLE
Subghz Saved 

### ISSUE THREAD

**Issue by Retaliation357** [Flipper-XFW/Xtreme-Firmware#338]
### Describe the bug.

Not sure if this has to do with the firmware, but every time I go to subghz saved, send out a signal, back out all the way, then go back to saved and it loads me to the signal I just sent instead of showing me all my saved options. I installed the firmware again to see If maybe it would fix it but It still does the same thing.

### Reproduction

Go to Subghz
 Scroll to 'Saved' 
Send out any signal 
Back out all the way 
Go back to Subghz Saved

**Comment by ClaraCrazy** [comment]
Cant replicate, works just as intended
