### ISSUE TITLE
transfer the recorded signal to the control

### ISSUE THREAD

**Issue by Hitmanreis** [Flipper-XFW/Xtreme-Firmware#339]
### Description of the feature you're suggesting.

I'm trying to transfer the decoded or raw fixed code signals that I captured with flipper zero to the remote, but the remote doesn't read these signals, is there a way to transfer it?

https://www.google.com/search?q=433mhz+remote&client=ms-android-xiaomi-terr1-rso3&prmd=sivn&sxsrf=AB5stBi8hnHi2ErNd5YhuXzGPzB1fMd0DA:1690299508818&source=lnms&tbm=isch&sa=X&ved=2ahUKEwi82KSumKqAAxVrSfEDHdBbB7MQ_AUoAnoECAIQAg&biw=407&bih=772&dpr=3#imgrc=-5XpsoDvBDOX-M

**Comment by Hitmanreis** [comment]
Çözümün var mı?

**Comment by Hitmanreis** [comment]
do you have a solution?

**Comment by Zarcolio** [comment]
> ### Description of the feature you're suggesting.
> 
> I'm trying to transfer the decoded or raw fixed code signals that I captured with flipper zero to the remote, but the remote doesn't read these signals, is there a way to transfer it?
> 
> https://www.google.com/search?q=433mhz+remote&client=ms-android-xiaomi-terr1-rso3&prmd=sivn&sxsrf=AB5stBi8hnHi2ErNd5YhuXzGPzB1fMd0DA:1690299508818&source=lnms&tbm=isch&sa=X&ved=2ahUKEwi82KSumKqAAxVrSfEDHdBbB7MQ_AUoAnoECAIQAg&biw=407&bih=772&dpr=3#imgrc=-5XpsoDvBDOX-M

You're trying to send a recorded signal to an RF remote???
That does not make any sense 🤔
A remote sends a signal to a devices.
A Flipper Zero can record this signal and act as a remote replacement.
A universal IR remote might be configured by sending an existing signal but an RF remote?
Also, how does a Google query for "433mhz remote" help? 🤷‍♂️
Maybe you could clarify your wish?
