### ISSUE TITLE
NFC Fails to load keys

### ISSUE THREAD

**Issue by benjaminkovacevic** [Flipper-XFW/Xtreme-Firmware#346]
### Describe the bug.

Both Xtreme and Unleashed firmware have bugs when reading NFC keys.

It would display that keys are missing even though they are correct, like so:
31/32 keys found
15/16 sectors read

The key it fails to load is key B on sector 1 in my case specifically. It does not necessarily have to be sector 1, but it is always key B.
I know for a fact that the key B is correct, moreover it's the same as key A which was found successfully.

I noticed it only produces this bug when the key is added to dictionary by FlipperNested or manually.

Once the Flipper firmware is updated to the original one, all keys are listed as found.

Tried 2 different cards with same problem.

### Reproduction

Switch on
Get a card with an unknown key for one of sectors (should be out of dictionary).
Obtain the key using Flipper Nested Attack
Once its sucessfully found and added to dictionary, try reading the tag again
If keys are still not found when reading, installing the original firmware will fix the problem

### Anything else?

it might has something to do with flipper nested cache, or the device cache itself

**Comment by d2thunder** [comment]
Hi,

Have the same Problem today.
It doenst matter in wich way the key is added to the dict_user.
Its always key b. I cleard both lists, controlled codepage and used curragereturn+linefeed and linefeed anlone - all doenst matter.

Another thing i saw, it thale much morentime to test the keys vs sektors.

In unleashed it works with today firmware, think it was a bug from original fw?

**Comment by Willy-JL** [comment]
Judging the name i would assume it is something to do with this commit: a7aef0bfc27541639aa7be0cfc06a2db0ecc8c9a

And it being "key invalidation" that had issues, it would make sense that it randomly stopped working after some time, even if the bug was already there... it sounds like a bug that shows itself later on. But I am no NFC expert.

Gonna mark this as release-pending, comment again if it is still not fixed

**Comment by Willy-JL** [comment]
should be fixed in v51. try it and let us know

**Comment by benjaminkovacevic** [comment]
Had no problems so far. Thank you
