### ISSUE TITLE
Installing apps via the official flipper iPhone app 

### ISSUE THREAD

**Issue by mmoti6** [Flipper-XFW/Xtreme-Firmware#347]
### Describe the bug.

I have a flipper zero with xtreme 27.7.23
And when I connected to the official flipper app in iPhone I can't install apps 
The app simply doesn't show me the apps that's available 
If i disconnected the flipper i can see the apps

### Reproduction

1.connect flipper zero with xtreme with iPhone in the official app

**Comment by Willy-JL** [comment]
blame OFW. they made it as annoyng as possible. basically the version number is off by 0.1... it wouldwork werent it for the number. it is "fixed" in dev branch, either use the dev builds on discord, or wait for an update

**Comment by Willy-JL** [comment]
fixed in v51
