### ISSUE TITLE
NFC Emulation Causes Crash

### ISSUE THREAD

**Issue by huntyboy102** [Flipper-XFW/Xtreme-Firmware#349]
### Describe the bug.

When emulating an NFC tag there is a chance that Xtreme will hang. The only way to exit the emulator is to force a reboot

### Reproduction

Switch on
Press the middle button
Go to NFC
Go to Saved
Find a tag to emulate
Repeat untill crash

### Target

XFW-0050 27-07-2023

**Comment by Willy-JL** [comment]
way to provide no useful details at all

**Comment by ClaraCrazy** [comment]
I've been emulating signals for the last 6 Minutes now, could not get it to hang even once. Other staff hasnt gotten it either.
