### ISSUE TITLE
Sub GHz external module RF test app

### ISSUE THREAD

**Issue by Speedjet2000** [Flipper-XFW/Xtreme-Firmware#350]
### Description of the feature you're suggesting.

It would be fantastic to introduce a simple app that allows users to test the efficacy of external antennas and RF modules such as the CC1101. 

The option to be able to select an operating frequency and test RX and TX would be awesome. As someone that is interested in the RF capability of the Flipper and the development of antennas this functionality would be super useful.

**Comment by Speedjet2000** [comment]
Why was this feature request closed?

**Comment by Willy-JL** [comment]
did you read the comment?

**Comment by ClaraCrazy** [comment]
Clearly he did not

**Comment by Speedjet2000** [comment]
Yes I did. And its n to a duplicate!

**Comment by Sil333033** [comment]
n to

**Comment by ClaraCrazy** [comment]
n to

**Comment by Willy-JL** [comment]
n to

**Comment by Speedjet2000** [comment]
Seriously! what's the problem guys? I'm new to this and never posted in Github before. I'm super interested in the Flipper Zero and its capabilities So far all I've been met with is hostility and rude comments! why is that?

**Comment by ClaraCrazy** [comment]
There wasnt a single rude comment or hostility. I think your mainframe is corrupt and needs a rewrite.

**Comment by Speedjet2000** [comment]
So picking up on my typo's and reposting them isn't rude?!!! You guys are supposed to be the experts here and should be encouraging/guiding people. So can we start again?? Please tell me why my feature request was closed. Thanks

**Comment by Sil333033** [comment]
I'm sorry. I thought it was a fun joke. This feature request is deleted because it's useless. Read here for more information [https://github.com/Flipper-XFW/Xtreme-Firmware/issues/348](url) (The other issue where everything is explained) Still thanks for the feature request! If you have any other improvements just let us know!

**Comment by Speedjet2000** [comment]
I commented on the other post. I don't find it useless at all, I used it just today to test the power output of a UHF amplifier board that I'm currently working on. My request was not to leave the 'Test' feature in but to develop a new app for the Flipper to make it even better 😎

**Comment by Sil333033** [comment]
Amplifier boards are always nice. I would recommend a RAW SubGHz file with junk data. I use that myself and i get a pretty nice view of my output power. 
![higain](https://github.com/Flipper-XFW/Xtreme-Firmware/assets/94360907/1d2fea8d-43a0-4968-8a44-8e21022832f8)

**Comment by fry9** [comment]
That's a really interesting setup you have there! Are you willing to elaborate a bit about the components that you use?

I've been interested in trying SubGHz amplifier boards, and been looking for some information about what to get. I don't have the Rabbit-Labs module but a few other generic external CC1101 modules and antennas. What kind of wideband power amplifier board is suitable? Is it better with one with a more narrow frequency like 1M-2GHz than 5M-6GHz? What is important? And is that last big board another amplifier, so you have two of them changed?

Sorry for all the questions, maybe it's not suitable here.
But, many thanks for any help.
