### ISSUE TITLE
Opening subghz file from favorites plays the file repeatedly automatically

### ISSUE THREAD

**Issue by PowerUser64** [Flipper-XFW/Xtreme-Firmware#360]
### Describe the bug.

When opening a subghz file from the favorites menu, it is automatically played. Not only that, the file is repeated until the application is exited, which oddly enough can be done by pressing the center button (normally this button would play the file).

This is only the case when opening subghz files from the favorites menu, opening them directly from the subghz application does not result in this problem.

### Steps to Reproduce

1. Add a subghz file to favorites
2. Open the file from the favorites menu
     - it will play automatically, but it shouldn't
     - it will also play repeatedly, which would only happen under normal circumstances if the center button was being held down
4. Press the center button
    - this exits but it shouldn't (normally this is the play button and the back button exits)

### Target

n/a?

### Logs

n/a

### Anything else?

This was introduced as a regression in the latest release.

**Comment by Willy-JL** [comment]
It's not a big. YOU enabled "favorite timeout". This is exactly what it does. Runs the file for the amount of seconds you set when you run the file from favorites.

**Comment by PowerUser64** [comment]
Oh! my bad. I didn't know that's what that setting did! Thanks for letting me know!
