### ISSUE TITLE
NFC-B, V, F would be nice to handle :)

### ISSUE THREAD

**Issue by bip3r** [Flipper-XFW/Xtreme-Firmware#363]
### Describe the enhancement you're suggesting.

Flipper can read and show NFC-B UID but it cant save it nor emulate.

If it's only a matter of software It would be great to handle these types of NFC too.

**Comment by ClaraCrazy** [comment]
some are done, the rest wont be done anytime soon by official or anyone else for many reason a simple google search would tell you.
