### ISSUE TITLE
Flipper zero's own keylogger app

### ISSUE THREAD

**Issue by Josepk23** [Flipper-XFW/Xtreme-Firmware#364]
### Description of the feature you're suggesting.

Since the flipper is capable of many amazing things, I was wondering if it would be possible to make some sort of keylogger app for the flipper. Or use the flipper itself as a keylogger. I know it may be unlikely to be possible since for a keylogger it needs to be plugged in to the computer and the keyboards itself. But maybe someone will come up with a solution?

**Comment by Willy-JL** [comment]
How it could be possible is by wiring up a usb socket via GPIO and plug the keyboard into that, then plug flipper into the PC. Then write a new app that reads the keyboard inputs from GPIO, logs them, then forwards them to the PC via usb. Very convoluted, needs more hardware, and not planned
