### ISSUE TITLE
Can't open Hub in mobile app

### ISSUE THREAD

**Issue by vstkl** [Flipper-XFW/Xtreme-Firmware#365]
### Describe the bug.

With official firmware it works as it should, but mobile app looks like it keeps refreshing for some reason, if someone has some pointers where to look I'd gladly try to fix the bug. 
I think the hub feature is quite new, I am not really following the updates and just play around with my flipper, as I said, advice appreciated and i will gladly fix it

### Reproduction

1. Open mobile Flipper App on iPhone
2. Click on hub
3.  Nothing appears

### Target

Mobile App

**Comment by Willy-JL** [comment]
Duplicated of #347

**Comment by vstkl** [comment]
thansk for clarification! @Willy-JL
