### ISSUE TITLE
HDN_2 modulation is missing

### ISSUE THREAD

**Issue by theflyingsquirrel88** [Flipper-XFW/Xtreme-Firmware#366]
### Describe the bug.

Hi was reading the menu and it mentioned HDN_2 modulation in SubGHz. But I only see HDN_1. How do I enable the HDN_2?

### Reproduction

Try to Read from SubGHz. Choose configure and try changing modulation to HDN_2.

**Comment by Willy-JL** [comment]
HND_2 causes memory leaks and corruption, was removed for that reason. there was little point to it anyway. use HND_1

**Comment by Willy-JL** [comment]
more info here: DarkFlippers/unleashed-firmware#506

**Comment by theflyingsquirrel88** [comment]
Oh I see. Thanks for the information.
