### ISSUE TITLE
Mass Storage 

### ISSUE THREAD

**Issue by spyro12675** [Flipper-XFW/Xtreme-Firmware#368]
### Describe the bug.

i have the new update on my flipper and when i click on mass storage it doesnt show anything
![Screenshot-20230826-174609](https://github.com/Flipper-XFW/Xtreme-Firmware/assets/57742974/157da3fb-478a-43ff-b385-0c56beb69b39)
![Screenshot-20230826-174618](https://github.com/Flipper-XFW/Xtreme-Firmware/assets/57742974/1ca10440-c94a-41ac-afcb-c03d765edd27)
![Screenshot-20230826-174623](https://github.com/Flipper-XFW/Xtreme-Firmware/assets/57742974/3943dcb6-97c8-4337-a488-4189c8e2508e)

### Reproduction

1.USB
2.Mass Storage
3.Nothing

**Comment by ClaraCrazy** [comment]
thats not a bug. it works by adding an img file to it.

**Comment by ClaraCrazy** [comment]
@Willy-JL can explain things a lot better, so ig wait for him to wake up.

**Comment by Willy-JL** [comment]
Yeah. Mass storage simply emulates a disk image. You need to give it a .img file and it will use that to emulate a usb drive. That .img file is essentially the raw data that you would have on the drive, not files and folders themselves, but the 1s and 0s that make them up. On the current v50 release, you need to make an image file yourself and upload it to flipper. On dev branch there is an option to create an empty disk image directly on flipper with the size you want.
