### ISSUE TITLE
Magspoof.fap not works, but it worked before

### ISSUE THREAD

**Issue by ptasema** [Flipper-XFW/Xtreme-Firmware#369]
### Describe the bug.

Error

Load failed magspoof.fap Found unsatisfied imports

### Reproduction

Install and run fap

**Comment by ClaraCrazy** [comment]
Not a bug, if you dont compile the app with our sdk ofc it wont work.

**Comment by Willy-JL** [comment]
>install an outdated app compiled for an old version
>app does not work
>surprised pikachu face
FYI it's included in xtreme now, will be in next release
