### ISSUE TITLE
LCD backlight problem

### ISSUE THREAD

**Issue by sariyan-0** [Flipper-XFW/Xtreme-Firmware#375]
### Describe the bug.

I recently updated my flipper and now the lack light stays on even after the timeout and im keep restting my flupper and reinstalling the OS and nothing changes and I have even switched to the flippers original OS and the screen timeout works and it only happens on the new xtreme update.

### Reproduction

No idea!

**Comment by Willy-JL** [comment]
disable the "rgb backlight". you do not have an rgb backlight. you have a regular backlight. when you enabled it, you were warned about this.

**Comment by Willy-JL** [comment]
you can find it in Xtreme > Misc > Screen > RGB Backlight
