### ISSUE TITLE
Barcode light adjustment

### ISSUE THREAD

**Issue by Qreed213** [Flipper-XFW/Xtreme-Firmware#376]
### Describe the enhancement you're suggesting.

I use a 5-10% brightness defualt.

when i use the barecodes i forguett that 5% light is to low read so i need to go back to settings sett the brightnes to 100% then go to the correct barcode and scann.

can ther be a brigthness level like in the clock (( When pressing left buttorn ther is a clock and date with light adjustment upp and down that only affect that application)) 

guess this it is good for some other apps to like QR but its barecode i use the most.

love the work that is done so far :D

**Comment by MatthewKuKanich** [comment]
Just submitted a PR to the original repo adding a brightness change when viewing barcodes

**Comment by Qreed213** [comment]
Im not so used to git, but i understand than it is the better aprotch to contact the orginal maker.

**Comment by MatthewKuKanich** [comment]
> Im not so used to git, but i understand than it is the better aprotch to contact the orginal maker.

What I'm saying is that I submitted a fix to the original dev. If he deems it good, then he will merge it with his, and it will be pushed as the official release. Until then, you can compile the fixed fap from here: https://github.com/MatthewKuKanich/flipper-barcode-generator
