### ISSUE TITLE
BLE Spam notification popups

### ISSUE THREAD

**Issue by wmorgue** [Flipper-XFW/Xtreme-Firmware#379]
### Description of the feature you're suggesting.

Hello 👋
 it is possible to implement support for Bluetooth Low Energy (BLE) and ADV Packets for spam Apple AirDrop, Keyboard, TV, etc. ?

Article: https://techryptic.github.io/2023/09/01/Annoying-Apple-Fans/

**Comment by Willy-JL** [comment]
its already in our dev branch, with 100x more features than in that article

**Comment by HarryHarmsen** [comment]
When does the New Firmware be released? Otherwise how can i use the Apple BLE feature now? Greetings from germany

**Comment by Willy-JL** [comment]
When it's ready. For now use dev builds

**Comment by HarryHarmsen** [comment]
Thanks for the Reply. IWhere can i download the Developer Build? i just find the normal Xtrem Firmware from 1 Week ago.

**Comment by Yn-Skr** [comment]
where exactly on the actions ?

**Comment by Willy-JL** [comment]
Click on the builds section, then click on any of them and click on the artifact to download it
