### ISSUE TITLE
[ESP32] WiFi Marauder app is missing in XFW-0051 01-09-2023

### ISSUE THREAD

**Issue by iftsv** [Flipper-XFW/Xtreme-Firmware#387]
hello,
I flashed latest version of Xtreme-Firmware XFW-0051 01-09-203 and also flashed DevBoard according to this manual https://github.com/Flipper-XFW/Xtreme-Firmware/wiki/Generic-Guides
But when I open Apps section, I can't find [ESP32] WiFi Marauder app to work with flipper WiFi Devboard. Could you please help me? Thanks in advance

**Comment by N-coder82** [comment]
It's in  new section called Wi-Fi, scroll ALL the way down

**Comment by N-coder82** [comment]
Confused me also!

**Comment by Willy-JL** [comment]
we really gotta remove those generic guides...

**Comment by N-coder82** [comment]
> we really gotta remove those generic guides...

What do you mean?

**Comment by Willy-JL** [comment]
that was some random bs that dyiing wrote on discord 7 months ago, then ported to the wiki and then stopped updating, now doesnt even have anythign to do with us anymore. and there are better guides elsewhere, there are just misleading since they are plain outdated

**Comment by N-coder82** [comment]
Oh, ok, also wanted to ask: am I allowed to help with the wiki?

**Comment by iftsv** [comment]
@N-coder82 @Willy-JL oh, really thanks for fast reply and your work, have a n1c3 day ^)
