### ISSUE TITLE
Bug with Discord Verify bot

### ISSUE THREAD

**Issue by ZekePolarisBSH** [Flipper-XFW/Xtreme-Firmware#389]
### Describe the bug.

It keeps saying it is typed wrong but it is not. Am I going to get banned from the server?

### Reproduction

Joined
Verify
Bot fails test?

**Comment by ClaraCrazy** [comment]
![IMG_20230911_033145.jpg](https://github.com/Flipper-XFW/Xtreme-Firmware/assets/55334727/4684ea4c-d3e7-4492-bdd3-11c7df8a6463)

![IMG_20230911_033134.jpg](https://github.com/Flipper-XFW/Xtreme-Firmware/assets/55334727/7140731b-c9f0-4680-85fb-bdb72f64e646)

your stupidity is not a bug

**Comment by ZekePolarisBSH** [comment]
Weird I typed it with F each time. Idk why the second one does not have F
in it. The first one was because my caps was already locked and I unlocked
it by accident. It isn't stupidity, it is called a mistake.

**Comment by ZekePolarisBSH** [comment]
Also you removed something of yours's after a channel said something about it.

**Comment by ClaraCrazy** [comment]
dafuq did I remove? nothing...

**Comment by ClaraCrazy** [comment]
and yes... a "mistake"

*I typed the captcha wrong... must be a bug, lets waste their time on github instead of using my eyes and brain*

**Comment by ZekePolarisBSH** [comment]
Calm down, it was a CFW with all animations and not a mistake with me, a
mistake with the keyboard. I have missing keys here.... Sas shared it
saying it was by you. And I can read it I was just wondering if one makes
too many wrong guesses would the bot ban them. That's all what I was
wondering. No need to get hostile for no reason.

**Comment by ClaraCrazy** [comment]
We didnt remove anything. dunno what sas has to do with any of this either.

**Comment by ZekePolarisBSH** [comment]
Are you saying you don't know Talking Sasquach? If you didn't removed
anything what happened to the CFW?...

**Comment by ClaraCrazy** [comment]
bro speak english lol. Nothing got removed, nothing happened. what are you talking about? jesus fucking christ... no way in hell you're even 18+

**Comment by ZekePolarisBSH** [comment]
I can't speak I can only type don't harass others because they are
disabled. Are you trolling me? You ignored the channel name after asking
about it. If I am not 18+ then you must be 9 because no one types like that
and talks down on other's English. For someone that is claiming that I am
not 18+ you sure need to grow up before talking. And yes something was
deleted. If not by you then by someone else that works on it. I never said
you directly but for you to get all defensive tells me otherwise. Specially
if you just going to think someone that is older than you can't be 18+. 🤣

**Comment by ClaraCrazy** [comment]
"harass" 🤡

**Comment by ClaraCrazy** [comment]
and since you clown are still too mentally slow and incompetent to just *fucking say* what was supposedly deleted, because none of us can read your useless mind... I cant help you. Have a great day, I'm praying that it rains brain today and you catch one
