### ISSUE TITLE
Cant install apps from yhe flipper "app store"

### ISSUE THREAD

**Issue by devicemodder** [Flipper-XFW/Xtreme-Firmware#393]
### Describe the bug.

I'd love to be able to install apps from the "app store" that's in the flipper mobile app while keeping xtreme. 

Is there any way to accomplish this?

### Reproduction

Open flipper phone app, go 
![Uploading Screenshot_20230916_155923_Flipper.jpg…]()
to Hub > Apps. "Not compatible with your firmware"

**Comment by Willy-JL** [comment]
this is because OFW updated, and we haven't yet. wait for a new release, or use the latest dev build.

**Comment by devicemodder** [comment]
Ah, didn't know that. I'll wait then. Thanks for letting me know.

**Comment by dedsecproyt** [comment]
You can use my dev build from [My Workflow build](https://github.com/dedsecproyt/Flipper_Frimware/releases/tag/main)

**Comment by Willy-JL** [comment]
No. You can use the official dev builds made by us, the xtreme team, in the official xtreme discord server, on in the official xtreme GitHub actions

**Comment by dedsecproyt** [comment]
> No. You can use the official dev builds made by us, the xtreme team, in the official xtreme discord server, on in the official xtreme GitHub actions

But its work well, i use my build
PS. wery happy because I can make updates via GitHub +- 10 minutes goes to build

**Comment by Willy-JL** [comment]
...
thats literally what we already made. months ago. shipped directly to discord. single click download. by someone reputable.

**Comment by dedsecproyt** [comment]
> ... thats literally what we already made. months ago. shipped directly to discord. single click download. by someone reputable.

But you probably can't make custom builds, for example without games or extra plugins...

**Comment by Willy-JL** [comment]
you can do what you want on your own. the code is open for that reason. but you are not gonna suggest your random repo builds as an alternative to the official ones

**Comment by dedsecproyt** [comment]
> you can do what you want on your own. the code is open for that reason. but you are not gonna suggest your random repo builds as an alternative to the official ones

Good, but if anything, you can still use your own build as an alternative for now...
