### ISSUE TITLE
Apple airtag emulation would be nice

### ISSUE THREAD

**Issue by devicemodder** [Flipper-XFW/Xtreme-Firmware#394]
### Description of the feature you're suggesting.

see here: https://github.com/culturally/flipper-zero-airtag
https://techryptic.github.io/2023/09/01/Annoying-Apple-Fans/

Would love to have this feature

**Comment by ClaraCrazy** [comment]
this is our code that techryptic stole. 

https://willyjl.dev/blog/the-controversy-behind-apple-ble-spam

**Comment by Willy-JL** [comment]
i will expand on this a little bit. you are looking at 2 very different things.

the second, by techryptic, is *not* airtag tracking. it emulates the airtag popup, thats it. and as clara said, techryptic didnt make or discover it. he claimed other people's code as his own, and showcased our app which could spam popups, while "his" could not.

the first one, however, is more legitimate. that code was written by (and is credited to) salmq, and emulates the tracking beacons of airtags, not the popup beacons. however, that method is not very user friendly as it requires recompiling the firmware, and removes support for the mobile flipper app. also going and editing around in gap.c with little understanding of it is a bad idea.

we plan on making a generic ble app that can use custom advertisement files in background, and that could be useful to emulate your own airtag tracking beacons.

**Comment by devicemodder** [comment]
Thanks for clearing that up. Yes, I am looking to emulate airtags. Glad to
know it's gonna be in a  future firmware release (saw another issue thread
where it was mentioned). Sad to hear that it was stolen from you as Xtreme
is a great firmware.
