### ISSUE TITLE
Automatic bleeding edge releases

### ISSUE THREAD

**Issue by molangning** [Flipper-XFW/Xtreme-Firmware#395]
There is a automatic github actions that builds the firmware at https://github.com/Flipper-XFW/Xtreme-Firmware/actions/runs/6209401149 
From what I can see, all files are built in there. Is there a way to publish them in releases so that bleeding edge releases lovers get to experience the latest firmware?

**Comment by molangning** [comment]
to clarify, I can download it directly from the builds but having it in releases will be nice as it is more convenient

**Comment by ClaraCrazy** [comment]
its not a release tho, so its not in the release tab.

just use the discord bot that keeps sending the new one

**Comment by flipperuser256** [comment]
Is there no other way than discord? Because I'm unable to join the discord... ;(

**Comment by Willy-JL** [comment]
https://github.com/Flipper-XFW/Xtreme-Firmware/actions/workflows/build.yml

**Comment by molangning** [comment]
> Is there no other way than discord? Because I'm unable to join the discord... ;(

You can write a cronjob that checks for updates then alert you

Thats what I did anyways
