### ISSUE TITLE
SD Card not reading

### ISSUE THREAD

**Issue by Lorenzo2013460** [Flipper-XFW/Xtreme-Firmware#397]
### Describe the bug.

Okay, so the SD card, every time i put it in, when i start it up with it, it has the reading screen, stuck. After a bit, it says "Mounting SD Card failed". When i start it up without it, it will load up the menu, with the LED turning green, after a bit stopping, and green again, until the LED flashes red. The menu, has now only 3 apps: the settings, Xtreme settings and Apps.
Xtreme just says an error, Apps is just empty, but Settings works just fine.
I remember sometime when it happened the same, but when i reputted it in again, it worked. Now it doesn't anymore. Any help? 

### Reproduction

Putting the SD card before powering on:
1.Powering on
2.Stuck on the reading screen
3. After waiting, SD Card not mounter screen pops up

Not putting the sd card before powering on:
1.Powering on
2.Menu, with only 3 apps and sd card not mounted.

If i put it in:
1: LED flashes green, after a bit no more, and then green...
2: After failing, flashes red. 

### Target

SDCard

**Comment by ClaraCrazy** [comment]
buy a proper sd card that supports spi

**Comment by Lorenzo2013460** [comment]
> buy a proper sd card that supports spi

I have a Kingston sd card. Does it support SPI?

**Comment by ClaraCrazy** [comment]
https://google.com

**Comment by Lorenzo2013460** [comment]
> https://google.com

¯\_(ツ)_/¯

**Comment by Lorenzo2013460** [comment]
> https://google.com

Seems like i will have to find out myself :(

**Comment by jtbg** [comment]
@Lorenzo2013460 what specific model/specs is your Kingston microsd card?

**Comment by Lorenzo2013460** [comment]
> @Lorenzo2013460 what specific model/specs is your Kingston microsd card?

Where do i see it?

**Comment by jtbg** [comment]
Usually, the information is printed on the card itself. Besides the brand name Kingston, what else is written on the card?

**Comment by LorenzoBeep** [comment]
> Usually, the information is printed on the card itself. Besides the brand name Kingston, what else is written on the card?

Sry for answering for so long, on the front there is (under "Kingston") "SDCS/16GB" and under it "31662-003.A00LF" In the back, "CG 16G 1822" and under it "HVLKA86 109A 16" Maybe they mean **something?**
