### ISSUE TITLE
Epson projector universal remote not working

### ISSUE THREAD

**Issue by daemoncat** [Flipper-XFW/Xtreme-Firmware#400]
### Describe the bug.

Whenever i try to turn of an epson projector, it pops up the "Turn OFF?" dialog box around 60% but when i try to broadcast again the box is aready gone

### Reproduction

1. go to universal remote
2. find epson projector
3. go to projectors section
4. click turn off
5. wait
6. you have reproduced the bug

### Target

Universal Remote

### Anything else?

otherwise, amazing firmware i like the new gui compared to the normal flipper zero

**Comment by N-coder82** [comment]
That is the problem of the person who made the IR remote, not the Xtreme team

**Comment by daemoncat** [comment]
ok thx

**Comment by N-coder82** [comment]
No problem

**Comment by JCoulter85** [comment]
Latest iOS update made some of the Bluetooth controller options not work

**Comment by Willy-JL** [comment]
> Latest iOS update made some of the Bluetooth controller options not work

Make an appropriate issue, don't hijack unrelated issues.
