### ISSUE TITLE
Flipper Runs out of battery in a couple of days

### ISSUE THREAD

**Issue by aaronrolls** [Flipper-XFW/Xtreme-Firmware#402]
### Describe the bug.

A recent flipper update extended the flipper battery life to weeks. Initially this was the same on the xtreme firmware. Now my flipper will die in a couple of days. I’m assuming the optimisations have been removed from the firmware.

### Reproduction

Update to latest firmware.
Charge flipper to full.
Let it sit and wait

**Comment by ClaraCrazy** [comment]
no they havent

**Comment by Willy-JL** [comment]
Make sure debug is disabled
