### ISSUE TITLE
ESP-Flasher App

### ISSUE THREAD

**Issue by byFynn** [Flipper-XFW/Xtreme-Firmware#403]
### Describe the bug.

In the ESP-Flasher App the Bootloader doesnt work because its not doing anything.

### Reproduction

1. Turn on the Flipper
2. Go into the Apps -> ESP-Flasher
3. Connect your WiFi Devboard 
4. Try using the Bootloader function

**Comment by Willy-JL** [comment]
Not all boards are supported. Only the official Wi-Fi dev board from flipper is.
