### ISSUE TITLE
Please create telegram channel

### ISSUE THREAD

**Issue by d9j** [Flipper-XFW/Xtreme-Firmware#407]
### Description of the feature you're suggesting.

Discord seems going to downhill  with recent bugs and "features" .
 telegram appears to be best alternative.

**Comment by ClaraCrazy** [comment]
no

**Comment by d9j** [comment]
@ClaraCrazy seriously ? one person decision maker.  will never donate a cent

**Comment by ClaraCrazy** [comment]
oh, im sorry. wasnt aware you want @Willy-JL @Sil333033 and perhaps all community members to say no as well, hold on I'll do something rq :) 

also, dont care.

**Comment by SkeletonMan03** [comment]
> ### Description of the feature you're suggesting.
> 
> Discord seems going to downhill with recent bugs and "features" . telegram appears to be best alternative.
> ### Anything else?
> 
> _No response_

No

**Comment by finch-harold** [comment]
> ### Description of the feature you're suggesting.
> Discord seems going to downhill with recent bugs and "features" . telegram appears to be best alternative.
> 
> ### Anything else?
> _No response_

no

**Comment by mcurranseijo** [comment]
nay

**Comment by Brereid98** [comment]
> ### Description of the feature you're suggesting.
> 
> Discord seems going to downhill  with recent bugs and "features" .
> 
>  telegram appears to be best alternative.  
> 
> ### Anything else?
> 
> _No response_

No

**Comment by d9j** [comment]
ok. sorry for  seems to be dumb suggestion. and thank you for responses.

**Comment by N-coder82** [comment]
> ### Description of the feature you're suggesting.
> 
> Discord seems going to downhill  with recent bugs and "features" .
> 
>  telegram appears to be best alternative.  
> 
> ### Anything else?
> 
> _No response_

No

**Comment by htotoo** [comment]
big no

**Comment by d9j** [comment]
would anyone of you guys take time to explain  why no?

**Comment by Sil333033** [comment]
no @d9j

**Comment by Willy-JL** [comment]
no.
*refuses to elaborate*
![2D7C5442-78AE-499B-91E7-1F259F346DCA](https://github.com/Flipper-XFW/Xtreme-Firmware/assets/49810075/d48521dd-7d2d-43c1-bde2-554a0b48aded)

**Comment by d9j** [comment]
yes
