### ISSUE TITLE
Freeze screen in reset menu

### ISSUE THREAD

**Issue by ZhengLinLei** [Flipper-XFW/Xtreme-Firmware#409]
### Describe the bug.

The screen become frozen after entering in reset menu option to confirm or cancel the action.

### Reproduction

Go up.
Go Xtreme Settings
Enter Interface
Enter Mainmenu
Enter Reset menu

### Target

Xtreme Settings

**Comment by Willy-JL** [comment]
That most likely means that your sd card is corrupted. Try formatting it

**Comment by OkponkoXchange** [comment]
> That most likely means that your sd card is corrupted. Try formatting it
