### ISSUE TITLE
ESP-flasher stuck on waiting for HTML 

### ISSUE THREAD

**Issue by YannickHowest** [Flipper-XFW/Xtreme-Firmware#410]
### Describe the bug.

When I did quick flash to marauder and evil portal, it boots but gets stuck and says waiting on html. I dont know which html it means and how to give it. Anyone can help? I did move the ESP-flasher from gptio to WiFi in the apps section.

### Reproduction

1. esp flasher
2. quick flash
3. marauder+evil portal
4. boots
5. does some stuff
6. gets stuck on waiting for html

**Comment by Willy-JL** [comment]
Don't move apps. This will cause issues later on with updates.

Anyway, after opening the evil portal app try resetting the board (there's a button on the board) before clicking start portal
