### ISSUE TITLE
No apps shown up in the main menu on firmware Xtreme (Version: 51)

### ISSUE THREAD

**Issue by leolinchen** [Flipper-XFW/Xtreme-Firmware#419]
### Describe the bug.

When I download the Xtreme firmware via the chrome updater and the update is finished, the flipper zero shows in the main app menu just the apps: "Settings","apps"and"Xtreme". Sometimes broke the update process up and the flipper goes in the DEV-Modus.

### Reproduction

1.Open chrome  updater with newest version
2.plug your Flipper in
3.Dowload the firmware

**Comment by Willy-JL** [comment]
xtreme > interface > main menu > reset menu

**Comment by leolinchen** [comment]
Ty
