### ISSUE TITLE
Ability to modify RGB LED color schemes

### ISSUE THREAD

**Issue by Sn0w3W** [Flipper-XFW/Xtreme-Firmware#420]
### Describe the enhancement you're suggesting.

Hello!

Is it possible to implement an ability to change (add, remove, edit existing) color schemes for LCD LED with custom RGB values?

My screen become kinda blue-ish with White preset, so I want to calibrate it, add some new colors.

**Comment by ClaraCrazy** [comment]
use the dev build from discord.

**Comment by Sn0w3W** [comment]
@ClaraCrazy, I mean ability to modify these presets, not choosing them in Xtreme app.
<img width="724" alt="image" src="https://github.com/Flipper-XFW/Xtreme-Firmware/assets/57131742/b7e5d0f2-4ffc-40e8-8694-fc8aa3cbb62d">

I built and installed last dev. build form GH already, White preset is blue-ish compared to laptop screen:
![IMG_4309](https://github.com/Flipper-XFW/Xtreme-Firmware/assets/57131742/3d3bcc6f-75c3-4018-8bb8-1cb334c32228)

**Comment by ClaraCrazy** [comment]
you have the file open, why dont you modify it right there lol. Thats not doable to let users modify in code. Or just use your own custom preset like everyone else does and input hex. Also if that looks blue-ish to you then you might need glasses. Also also, you can literally see the rgb values for white. It doesnt get any whiter than that lol.

**Comment by Sn0w3W** [comment]
kthxbye

**Comment by ClaraCrazy** [comment]
🤨
