### ISSUE TITLE
animation: only the thank_you animation plays

### ISSUE THREAD

**Issue by leolinchen** [Flipper-XFW/Xtreme-Firmware#421]
### Describe the bug.

only the thank_you animation is playing on the screen, after I downloaded other animation to the flipper zero

### Reproduction

1. download custom animations
2. delete all the animation, which coming with the extreme firmware
3. rebooting the flipper

### Anything else?

can I delete the thank_you animation, that this animation will never play again?

**Comment by Willy-JL** [comment]
> download custom animations

theres your issue. chances are you did it wrong. wrong format, wrong place, or wrong manifest.

we have a solution to that, its called asset packs. just drop the files in and choose the asset pack you want to use in settings. can change on the fly. asset packs are at https://flipper-xtre.me/asset-packs but the website is currently down, so join the discord if you want them before we get the website back up
