### ISSUE TITLE
When is the next release coming out?

### ISSUE THREAD

**Issue by N-coder82** [Flipper-XFW/Xtreme-Firmware#429]
Hi, I was wondering when you guys are releasing the next version of XFW, just a question! Thank you!

**Comment by RChadwick7** [comment]
Ooh! I know!
When it's ready.

**Comment by xAstroBoy** [comment]
add a few months just because you asked, just use the dev builds

**Comment by N-coder82** [comment]
Yes, I am, was just wondering if there was a timeline, thank you!

**Comment by jb-deeper** [comment]
> add a few months just because you asked, just use the dev builds 

Where do you access the dev build download?

**Comment by Scrut1ny** [comment]
Their discord server via channel "#dev-updates"

**Comment by N-coder82** [comment]
Hi, just saw that #405 answered my question, thank you for answering so quickly!
