### ISSUE TITLE
I would like to point something out

### ISSUE THREAD

**Issue by tkbstudios** [Flipper-XFW/Xtreme-Firmware#432]
# Raiding RMs discord server is completely inappropriate and shouldn't be done, a new reason not to use your firmware..
## shame on you
![image](https://github.com/Flipper-XFW/Xtreme-Firmware/assets/69647028/1fc9fa2d-428c-474a-a6b9-ae7e24728965)
![image](https://github.com/Flipper-XFW/Xtreme-Firmware/assets/69647028/fe458cb6-7223-484f-a51b-0a65d9bf9348)
![image](https://github.com/Flipper-XFW/Xtreme-Firmware/assets/69647028/5815ace6-4b8b-488a-a57e-07e0c017b3fd)

**Comment by Willy-JL** [comment]
huh???

this has nothing to do with us?

complain to the people doing it, which is not us from the xtreme team.

**Comment by ClaraCrazy** [comment]
goofy ahh shit to wake up to...

**Comment by tkbstudios** [comment]
Yeah you guys woke me up too with your aggressive pings from your bots
