### ISSUE TITLE
Unable to connect bluetooth on Win11

### ISSUE THREAD

**Issue by ashhad** [Flipper-XFW/Xtreme-Firmware#435]
### Describe the bug.

I have just flashed the firmware and tried connecting the device to Bluetooth on my win11 machine. I get a prompt on the device with a PIN but when the same PIN is entered, I get an error (screenshot attached)

### Reproduction

1. Switch on Bluetooth
2. Find the device on the win11 machine
3. Click on Connect
4. Enter the PIN shown on FLipper device
5. Error message
6. 
![IMG_20231101_140944](https://github.com/Flipper-XFW/Xtreme-Firmware/assets/7990188/95687c53-3422-4a31-80fa-2138dbd0c64c)
![IMG_20231101_141000](https://github.com/Flipper-XFW/Xtreme-Firmware/assets/7990188/320ce0a8-7943-488e-a0c5-291210f1ae05)

**Comment by Willy-JL** [comment]
You need to set "Bluetooth devices discovery" to advanced in settings for it to show

**Comment by ashhad** [comment]
HI Willy,

It's already set to advance

![image](https://github.com/Flipper-XFW/Xtreme-Firmware/assets/7990188/58270b38-bc76-4611-8e47-bcac1b880538)

**Comment by Willy-JL** [comment]
Right... you are trying to pair the normal flipper connection. That doesn't work. You connect flipper to your phone, for the mobile app. Flipper doesn't work with pc over Bluetooth. You can connect it to pc Bluetooth if you are using badkb, bt remote, or similar things. But the normal flipper bt will not connect.
