### ISSUE TITLE
Genuinely can't decrypt the Discord Captcha

### ISSUE THREAD

**Issue by Kabouik** [Flipper-XFW/Xtreme-Firmware#436]
I am sorry to open a ticket for such a ridiculous issue, but I only have one attempt left on Discord, and if this is not `wdnP` or `wdmP`, then I really cannot tell what it is.

![ss20231101-140858](https://github.com/Flipper-XFW/Xtreme-Firmware/assets/7107523/a206168c-0011-4eb9-8254-86ad9b34e870)

Maybe `wzdmP`? But with only one attempt left, I'm not willing to try before I can make sure my Discord account won't be blacklisted from the server and prevented from another join attempt.

**Comment by Kabouik** [comment]
Apparently Discord expelled me before I could use my third attempt, and din't block me when trying the invitation link anew. That time, the captcha was clearer. Sorry for the noise.

A button to change captchas would be handy, but I suppose this is a Discord limitation.

**Comment by Willy-JL** [comment]
Failing the third time would've given a new captcha. It's 3 attempts per image, not before the end of the world
