### ISSUE TITLE
BT: OpenHaystack (Open-source AirTag)

### ISSUE THREAD

**Issue by spekulazarus** [Flipper-XFW/Xtreme-Firmware#445]
### Describe the enhancement you're suggesting.

I stumbled upon this repo [OpenHaystack](https://github.com/seemoo-lab/openhaystack) from [Alexander Heinrich](https://github.com/Sn0wfreezeDev), the author of [Who Can Find My Devices? Security and Privacy of Apple's Crowd-Sourced Bluetooth Location Tracking System](https://doi.org/10.2478/popets-2021-0045), which sounds super interesting regarding the Xtreme firmware.

Question/ feutre request: add openhaystack to Xtreme.

**Comment by Willy-JL** [comment]
Yes it's already in the tracker and already have another issue open somewhere
