### ISSUE TITLE
BadKB / BadUSB known bug with lack of DELETE 

### ISSUE THREAD

**Issue by nomad-c** [Flipper-XFW/Xtreme-Firmware#460]
### Describe the bug.

no way to issue ALT CTRL DELETE and as script sends backspace instead of DELETE

### Reproduction

everything described and fixed here:
https://github.com/flipperdevices/flipperzero-firmware/issues/2220

not fixed in Extreme firmware

**Comment by ClaraCrazy** [comment]
quite literally in the firmware and working

**Comment by ClaraCrazy** [comment]
https://github.com/Flipper-XFW/Xtreme-Firmware/blob/dev/applications/main/bad_kb/helpers/ducky_script_keycodes.c

**Comment by nomad-c** [comment]
Sorry - found it - my mistake

**Comment by nomad-c** [comment]
My mistake
was editing different file than running 
Sorry
