### ISSUE TITLE
BLE Spam remembers settings

### ISSUE THREAD

**Issue by fastnlight0** [Flipper-XFW/Xtreme-Firmware#465]
### Describe the enhancement you're suggesting.

The most optimal proximity pair combo is AirPods pro with "not your device" prefix. However, for me to use this, I have to navigate to the proximity pair section and click and hold ok, set the settings, and then I can initiate the attack. Could the BLE Spam app remember my previous settings so I don't have to keep setting the device and prefix every time I open the app?

**Comment by Willy-JL** [comment]
Too much effort for too little purpose. Also, you don't need to change the prefix. It will use that exact one on auto. Just a matter of selecting the AirPods Pro's
