### ISSUE TITLE
IR Move Button Not Working

### ISSUE THREAD

**Issue by AbeNaws** [Flipper-XFW/Xtreme-Firmware#468]
### Describe the bug.

When trying to rearrange the buttons in an IR remote, they change, but the codes don't. The code stays in the position it was originally in. Then when you exit and go back in the buttons go back to where they were before you tried to move them.

### Reproduction

1. Go into an IR remote
2. Go into Edit
3. Use the Move Button option to move buttons around
4. Go out of the remote and back in and the buttons will have reset to the position they were in before editing.

### Target

Infrared

**Comment by Willy-JL** [comment]
Fixed via e0fa360640b4e8d3c1f419bec8c8425895bb11be.

Issue was only present in dev branch, closing now
