### ISSUE TITLE
NFC: Redo EMV support (shows as unknown iso14443-4a)

### ISSUE THREAD

**Issue by TheRealNox** [Flipper-XFW/Xtreme-Firmware#469]
### Description of the feature you're suggesting.

Not too sure if I just can't find the option anymore, but we used to be able to read EMV card like bank card and see the card number displayed on the flipper zero.
Any chance to bring that feature back?

**Comment by TheRealNox** [comment]
Just saw in the tracker that a rework is already in progress, so maybe we can close this issue?

**Comment by Willy-JL** [comment]
its not resolved so it stays open, but yes this is planned. will take a lot of effort and time, might not make this next release.

**Comment by feinfeinfein** [comment]
This was the coolest feature imo, the ability to read the credit card number and expiration date.. Glad it's coming back.

**Comment by cubanhakr** [comment]
Any idea if there's a custom firmware that has worked? Ive tried multiple and keep getting the same ISO14443-4A code when scanning NFC.

**Comment by shego-zett** [comment]
Yes the RogueMaster one is able to do it and nested also works.

**Comment by ClaraCrazy** [comment]
> Yes the RogueMaster one is able to do it and nested also works.

Yes, because hes running 3 month old ofw code

**Comment by ClaraCrazy** [comment]
meanwhile we have almost emv working on the new code

**Comment by shego-zett** [comment]
Sorry didn't think of that... and thank you Clara and the rest of the Xtreme Team!

**Comment by breaky2023** [comment]
Nicely said ;)

**Comment by Schofrenzy** [comment]
Cuban yeah rouge master reads EMV still

**Comment by Willy-JL** [comment]
> Cuban yeah rouge master reads EMV still

No shit, hasn't updated in 3 months 😂

**Comment by Willy-JL** [comment]
leptoptilos implemented EMV again (with mroe features than before too, transactions and PIN attempts), now available in dev build

**Comment by shego-zett** [comment]
thanks for your great work!

WillyJL ***@***.***> schrieb am Mi., 31. Jan. 2024, 03:49:
