### ISSUE TITLE
SubGhz Bypass 

### ISSUE THREAD

**Issue by Alpha-404** [Flipper-XFW/Xtreme-Firmware#483]
![flpr-2023-12-09-22:26:09.png](https://github.com/Flipper-XFW/Xtreme-Firmware/assets/63340001/73515809-d964-4c1e-b015-e70fb1c7c39e)

SubGhz Bypass missing

**Comment by Sil333033** [comment]
Why do you want subghz bypass?

**Comment by Alpha-404** [comment]
I never said I did I just said I couldn't find it and that it's missing when it's stated on the wiki

**Comment by Willy-JL** [comment]
#439
