### ISSUE TITLE
Flipper shows sad animations when passport mood is happy 

### ISSUE THREAD

**Issue by Alpha-404** [Flipper-XFW/Xtreme-Firmware#484]

**Comment by Willy-JL** [comment]
just checked the manifest and all animations, this is not possible. all happy animations have butthurt levels of 0-14. the sad or angry animations have atleast 6-14, some more, but none can appear at less than butthurt 6. passport shows happy if equal or below 4 butthurt, okay if equal or lower to 9, angry if above that.

so what you are experiencing is not possible on the latest release. check that you are on the latest one and update if you are not.

if you are using an asset pack, state so the next time. asset pack butthurt levels need to be applied correctly by the asset pack creator.
