### ISSUE TITLE
Language

### ISSUE THREAD

**Issue by beyto0o** [Flipper-XFW/Xtreme-Firmware#489]
### Description of the feature you're suggesting.

I wonder if a Turkish language pack can be made?

**Comment by Willy-JL** [comment]
language packs are not really possible or feasible. switching on demand would most likely not be doable due to ram limitations. and editing all the existing apps and code to support a dynamic language system is really not feasible. and not to mention actually translating things.

**Comment by beyto0o** [comment]
thank you for the answer
