### ISSUE TITLE
Ability to write to NFC tags

### ISSUE THREAD

**Issue by AbeNaws** [Flipper-XFW/Xtreme-Firmware#493]
### Describe the enhancement you're suggesting.

Is it possible to  write to NFC cards similar to what some android phones can do?

**Comment by Willy-JL** [comment]
Yes. Recently with v52 the ability to write NTAG21X was added. That's the most common card type used for NDEF data like URLs, contacts, phone numbers, Wi-Fi logins, and so on. So just like on android apps.

You can even make an NTAG215 file using Apps > NFC > NFC Maker just how you want with whatever URL or info you like, then open the file in the NFC app and write it to a card/tag.
