### ISSUE TITLE
empty .pcap files on sd card

### ISSUE THREAD

**Issue by LinkseRat** [Flipper-XFW/Xtreme-Firmware#497]
### Describe the bug.

when i'm using the marauder firmware on the wifi dev board, i can do the sniffing but when i open qflipper and download those files, they are empty (0kb)

### Reproduction

1. flash wifi dev board with marauder firmware
2. hit reset on wifi dev board to reboot
3. unplug wifi dev board from pc
4. plug wifi dev board in FZ
5. start FZ
6. open Apps
7. scroll one up (or completely down, same thing) to WIFI
8. open WiFi Marauder
9. scan ap
10. select the relevant ssid in the list
11. scroll down to sniff
12. select any sniff method
13. after, go to qflipper
14. select the file manager tab
15. click on SD Card
16. click on Apps_data
17. click on marauder
18. click on PCAPS
19. right click file and download to specified folder
20. go to folder and see the empty files

### Anything else?

i tried several tips on reddit but they didn't work

**Comment by Willy-JL** [comment]
No.
1. Plug board to flipper
2. Apps > GPIO > ESP Flasher > Quick Flash > WiFi Dev> Marauder
3. When done, back out
4. Apps > WiFi > Marauder > Save to flipper > Yes to pcaps
5. Use sniff options, you get pcaps
