### ISSUE TITLE
UART bus fault with big amount of data

### ISSUE THREAD

**Issue by GoInK13** [Flipper-XFW/Xtreme-Firmware#500]
### Describe the bug.

With the application in *Apps/GPIO/[UART] UART Terminal*
I got the message 
```
Flipper crashed 
but has been rebooted
BusFault
```
when I sent a lot of data through UART.

### Reproduction

1. Go in *Apps/GPIO/[UART] UART Terminal*
2. Go in *Setup*
3. Set *UART Pins 13,14*
4. Set *Baudrate 115200*
5. Set *HEX mode OFF*
6. Connect GND (pin18) to GND of an UART device
7. Connect RX (pin 14) to TX of an UART device
8. Go in *Open port*
9. Wait for the crash, after receiving about 2800 characters.

### Target

Flipper Zero

### Anything else?

I love this firmware :-)

**Comment by WillyJL** [comment]
I'm fairly confident this is fixed after the expansion and uart refactoring fixes. Report back if still an issue
