### ISSUE TITLE
NFC - Failed identifying credit cards on latest XFW-0052_09122023

### ISSUE THREAD

**Issue by OscarAkaElvis** [Flipper-XFW/Xtreme-Firmware#503]
### Describe the bug.

On the latest firmware XFW-0052_09122023, the credit card detection by NFC is not working well. It was working on the older XFW-0051_01092023 firmware version.

This is the result of reading a credit card on this latest release (XFW-0052_09122023). It is unknown as you can see:
![image](https://github.com/Flipper-XFW/Xtreme-Firmware/assets/5803348/ef7639bb-5627-4e26-ae4d-128e294d088d)

This is the same credit card but using the September firmware release (XFW-0051_0109202):
![image](https://github.com/Flipper-XFW/Xtreme-Firmware/assets/5803348/fa19c16c-dda5-40f5-b511-641cc2b3ab75)

### Reproduction

1. Switch on
2. Enter on NFC menu
3. Launch the "Read" option while holding a credit card
4. Check the results.

**Comment by Sil333033** [comment]
i don't understand why you updated your flipper without reading the changelog🦐

**Comment by OscarAkaElvis** [comment]
I did quickly. Maybe I didn't notice that. Now I see it. Looking forward for the change. Sorry for the inconvenience.
