### ISSUE TITLE
cant write to nfc tag

### ISSUE THREAD

**Issue by Jona-Walpert** [Flipper-XFW/Xtreme-Firmware#505]
your card is locked by the lock bits. even with the passwords for all the pages you cant do anything. 
Those logs are useless btw, ignore them. They are referring to your actions via qflipper

_Originally posted by @Sil333033 in https://github.com/Flipper-XFW/Xtreme-Firmware/issues/504#issuecomment-1873296156_

**Comment by Willy-JL** [comment]
do not open a second issue.

**Comment by Jona-Walpert** [comment]
> do not open a second issue.

can a Issue be opened again after closed?

**Comment by Willy-JL** [comment]
if it has good reason to.

**Comment by Sil333033** [comment]
can a Issue be opened again after closed?

**Comment by Jona-Walpert** [comment]
> if it has good reason to.

I mean I still cant write to a nfc tag. the reading problem was just a misunderstanding

**Comment by Willy-JL** [comment]
stop talking here dude. take a goddamn hint.
