### ISSUE TITLE
Asset packer works with anims but not Icons

### ISSUE THREAD

**Issue by AustinRhoads** [Flipper-XFW/Xtreme-Firmware#507]
### Describe the bug.

I run the asset packer and it successfully converts the png files into .bmx. The animations work perfectly but for some reason it never uses the passport files just the default dolphin ones. Im sure my file structure is correct but just in case...

![Screenshot 2024-01-02 182022](https://github.com/Flipper-XFW/Xtreme-Firmware/assets/60074297/98b92427-571f-4df8-8919-07cae7d1450f)

### Reproduction

I used the method described in the XFW github page on assets (assets_packer.py).

**Comment by ClaraCrazy** [comment]
ofc they wont work, you changed their names. see https://github.com/Flipper-XFW/Xtreme-Firmware/tree/dev/assets/packs/WatchDogs/Icons/Passport 

Just change them back to the correct names :)
