### ISSUE TITLE
Question: Apple BLE spam different iOS version

### ISSUE THREAD

**Issue by mgrybyk** [Flipper-XFW/Xtreme-Firmware#516]
### Describe the enhancement you're suggesting.

Is it possible to have iOS Lookup Crash for iOS 16 in addition to 17?

I'm sorry if I didn't quite get how it works or something.

Thank you in advance!

### Anything else?

Many thanks to @Willy-JL and the team!

**Comment by Willy-JL** [comment]
Why would we purposefully limit it to just 17 if it worked on 16 too...?
