### ISSUE TITLE
Unable to open some sub-ghz apps

### ISSUE THREAD

**Issue by shmeebus** [Flipper-XFW/Xtreme-Firmware#518]
![Screenshot-20240114-020448](https://github.com/Flipper-XFW/Xtreme-Firmware/assets/155348817/dfb0ea6c-a349-48e3-b2c5-cd5c3ec66bf4)

also getting same message for POCSAG pager app...

**Comment by Willy-JL** [comment]
you need to update the app. the firmware is still compatible with this app. i just tested it. just install the new version from the official app hub.

however, there is not need to use that app. weather station, pocsag, and tpms are integrated into the normal subghz app. just do subghz > read.
