### ISSUE TITLE
ble_spam app fail XFW-0052_09122023

### ISSUE THREAD

**Issue by AIArt20** [Flipper-XFW/Xtreme-Firmware#522]
### Describe the bug.

The flipper ble_spam app fails in XFW-0052_09122023 or Apple/Android devices have been updated.

### Reproduction

Using the ble_spam app XFW-0052_09122023.

**Comment by Willy-JL** [comment]
did you expect it to work forever and apple/google/samsung/microsoft to never fix it? lol

will still work for some popups, but less most likely

**Comment by AIArt20** [comment]
this app than can be removed for no future use? lol

**Comment by Willy-JL** [comment]
I literally told you that it still works. Just less effective.

**Comment by Willy-JL** [comment]
No wonder such stupid logic comes from "AiArt20"

**Comment by AIArt20** [comment]
Less effective... lol, Id rather call it obsolete. But ok, ok, let's keep these nonsense.

**Comment by Willy-JL** [comment]
If you can't get it to work, you are the one less effective at using this "nonsense". Learn to read basic instructions, and maybe activate the 2 last remaining neurons in your brain
