### ISSUE TITLE
Obsolete App: ble_spam in XFW-0052_09122023

### ISSUE THREAD

**Issue by AIArt20** [Flipper-XFW/Xtreme-Firmware#524]
App is obsolete, bug has been fixed by multiple providers and the tool has no real use case left. Suggestion, remove app in repository and next update. 

Qoute:
If you can't get it to work, you are the one less effective at using this "nonsense". Learn to read basic instructions, and maybe activate the 2 last remaining neurons in your brain

_Originally posted by @Willy-JL in https://github.com/Flipper-XFW/Xtreme-Firmware/issues/522#issuecomment-1894191491_

**Comment by Willy-JL** [comment]
Congrats on getting blocked, knobhead.
