### ISSUE TITLE
Easy screen backlight off when Flipper is locked

### ISSUE THREAD

**Issue by Wwe1s** [Flipper-XFW/Xtreme-Firmware#528]
Right now if you want to turn screen backlight when Flipper is locked, you have to press up and then back if you use PIN or unlock and lock again if you don't use pin. Would be nice if pressing back on the lock screen would turn the backlight off.

**Comment by Willy-JL** [comment]
no? it stays on for a few seconds, then turns off. nowhere near the time it normally stays one while unlocked. no need for a button to turn it off when it already turns off very quickly.
