### ISSUE TITLE
Apps: BT/USB Remote: Change mouse jiggler distance back

### ISSUE THREAD

**Issue by Mfd81** [Flipper-XFW/Xtreme-Firmware#531]
### Describe the bug.

Mouse Jiggler not working on windows 11 over usb.

### Reproduction

1. use the mouse jiggler on windows 11

### Target

windows 11 pc

**Comment by Willy-JL** [comment]
Are you using the usb remote app? If so, do the other options work in it?

**Comment by Mfd81** [comment]
yes, and yes the mouse clicker and everything else works.

**Comment by Mfd81** [comment]
Thank You for the quick reply, Love the firmware too!

**Comment by Willy-JL** [comment]
It did change yes. I'll change it back after hearing this tho

**Comment by spralexx** [comment]
Can confirm. Getting logged of in Citrix. Has been working before.

**Comment by Willy-JL** [comment]
actually, nevermind. in the past it was 5 pixels jiggle. then with app migration and updates from upstream it became 1 pixel in the new apps repo, this is how it is in v52. but it has already been changed back to 5 pixels in dev branch. use the latest devbuild and let me know if it works, but it should.
