### ISSUE TITLE
esp32 wifi marauder broken since 052

### ISSUE THREAD

**Issue by SynthetikzZ** [Flipper-XFW/Xtreme-Firmware#535]
### Describe the bug.

just says load failed and to update the firmware and something about missingImports.

### Reproduction

load the app

**Comment by Willy-JL** [comment]
You are using the app in gpio folder. That is from another old firmware. Delete it. Xtreme puts it in the WiFi folder.

**Comment by SynthetikzZ** [comment]
oh for 051 it worked normally. thank you.
