### ISSUE TITLE
SubGHz is automatically creating RAW_ files

### ISSUE THREAD

**Issue by Aholicknight** [Flipper-XFW/Xtreme-Firmware#537]
### Describe the bug.

If you click "Read RAW" and then click the record button, wait a few seconds, click stop, exit, it will automatically save the RAW even when you do not click save. 

### Reproduction

1. Turn on the flipper
2. Goto the SubGHz menu
3. Click Read RAW
4. Start recording and wait a few seconds
5. Stop recording
6. Click the back button
7. Click exit
8. Goto saved
9. You will now see a new RAW_ file, which you did not ask to save.

### Anything else?

Nope

**Comment by Willy-JL** [comment]
seems like it uses the RAW_ file temporarily while you record since ram cant hold all that data. if you click erase instead of save, it goes away. issue is if you exit without clicking erase. should be easily fixed.
