### ISSUE TITLE
Nested nfc attack

### ISSUE THREAD

**Issue by fessnecro** [Flipper-XFW/Xtreme-Firmware#539]
### Description of the feature you're suggesting.

Can u add "Mfkey32 With nested" and "Mifare Nested" applications to NFC?

### Anything else?

Best firmware! Love u!

**Comment by Willy-JL** [comment]
Read the changelogs.

**Comment by Willy-JL** [comment]
Nested is broken and does not work on new NFC. There is a work in progress new nested implementation, that will be added when the developer completes it. Those 2 apps you say however, will not be updated to work, and are impossible to add.
